cakePHP課題の提出
mb-c16h18n3scl31985/quelcode-cakephp pull request #1
Opened 2021-01-05 07:57 UTC by mb-c16h18n3scl31985

- 詳細説明  
- 商品画像  

上記2点を追加して実装いたしました。  
ご確認どうぞよろしくお願い申し上げます。

2021-01-06 09:12 UTC, n06Ar requested changes
レビューしました。
確認をお願いします。
また、空ファイルを使って`webroot/img/biditem_image`ディレクトリがgit cloneした時に存在する状態にしてください。

2021-01-06 09:12 UTC, n06Ar commented on html/mycakeapp/src/Controller/AuctionController.php
> +                throw new \Exception("エラー説明");
このエラーの時に、エラーメッセージがエラー説明になりますが、問題ないでしょうか？

2021-01-06 09:12 UTC, n06Ar commented on html/mycakeapp/src/Template/Auction/add.ctp
> +    echo $this->Form->control('endtime', ['label' => '終了時間']);
初期表示で時間を選択するフォームではないのですが、問題ないでしょうか？

2021-01-07 11:49 UTC, mb-c16h18n3scl31985 commented on html/mycakeapp/src/Controller/AuctionController.php
> +                throw new \Exception("エラー説明");
編集漏れでした。失礼いたしました。
修正しました！

2021-01-07 12:02 UTC, mb-c16h18n3scl31985 commented on html/mycakeapp/src/Template/Auction/add.ctp
> +    echo $this->Form->control('endtime', ['label' => '終了時間']);
確認不足でした、申し訳ありません。

いつからこうなったのか不明なのですが、作成途中までは年/月/時間入力のフォームでした。
`control()`はカラムの型に沿ったフォームが形成されるため、
`datetime`型の`endtime`にはそれで合っているはずなのですが・・・。

データベースとの接続不良があるわけでもなく、
エラーログにもそれらしき記述が見当たりませんでした。


```
$this->Form->dateTime()
```
などとして強制的に時間選択のフォームとしても良いのですが、
理由を理解したく思います。
原因の予測として何かヒントをいただけないでしょうか？

2021-01-07 12:23 UTC, n06Ar commented on html/mycakeapp/src/Template/Auction/add.ctp
> +    echo $this->Form->control('endtime', ['label' => '終了時間']);
ヒントです
- Notice (8): Undefined variable: biditem [APP/Template/Auction/add.ctp, line 2] → NULL
- [Form - control()](https://api.cakephp.org/3.7/class-Cake.View.Helper.FormHelper.html#_control)

2021-01-09 00:24 UTC, mb-c16h18n3scl31985 commented on html/mycakeapp/src/Template/Auction/add.ctp
> +    echo $this->Form->control('endtime', ['label' => '終了時間']);
修正致しました。
ご確認お願い致します。


commit : 9fb8cdc

2021-01-09 00:25 UTC, mb-c16h18n3scl31985 commented
コメントいただいた点を修正いたしました。
ご確認よろしくお願い申し上げます。

2021-01-09 01:13 UTC, n06Ar approved these changes
LTGMです!
IMO的なコメントをしました。

2021-01-09 01:13 UTC, n06Ar commented on html/mycakeapp/src/Controller/AuctionController.php
> +            $connection = ConnectionManager::get('default');
tryの中に入れても良い気がしました。

2021-01-09 01:13 UTC, n06Ar commented on html/mycakeapp/src/Controller/AuctionController.php
> +            $connection = ConnectionManager::get('default');
tryの中に入れても良い気がしました。

2021-01-09 06:59 UTC, merged